package com.fiap.farmacheck.config;

import io.swagger.v3.oas.annotations.Hidden;
import io.swagger.v3.oas.models.*;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.tags.Tag;
import jakarta.servlet.http.HttpServletResponse;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@Hidden
@RestController
@Configuration
public class SwaggerConfig {
    @GetMapping("/")
    public void redirectSwagger(HttpServletResponse response) {
        String url = "/swagger-ui/index.html";
        response.setHeader("Location", url);
        response.setStatus(302);
    }

    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("FIAP - Tech Challenge - Fase 5 de Arquitetura e Desenvolvimento Java")
                        //.description("")
                        .version("v1")
                        .contact(new Contact()
                                .name("Farma Check")
                                .email("contato@farmacheck.com")
                                .url("https://github.com/offteuz/farma-check"))
                        .license(new License()
                                .name("Apache 2.0")
                                .url("https://www.apache.org/licenses/LICENSE-2.0.html"))
                )
                .components(new Components()
                        .addSecuritySchemes("bearer-key",
                                new SecurityScheme()
                                        .type(SecurityScheme.Type.HTTP)
                                        .scheme("bearer")
                                        .bearerFormat("JWT")))
                .addSecurityItem(new SecurityRequirement().addList("bearer-key"))
                .externalDocs(new ExternalDocumentation()
                        .description("Documentação Técnica Completa")
                        .url("https://github.com/offteuz/farma-check"))
                .addTagsItem(new Tag().name("Auth"))
                .addTagsItem(new Tag().name("Medicamentos"))
                .addTagsItem(new Tag().name("Estoques"))
                .addTagsItem(new Tag().name("Unidades"))
                .addTagsItem(new Tag().name("Movimentações"))
                .addTagsItem(new Tag().name("Testes"));
    }

    /**
     * Este bean roda DEPOIS que o Springdoc já escaneou os DTOs
     */
    @Bean
    public OpenApiCustomizer customApiPaths() {
        return openApi -> {
            openApi
                    // Auth
                    .path("/api/auth/sign-up", new PathItem().post(new Operation()
                                    .summary("Registra um novo usuário")
                                    .addTagsItem("Auth")
                                    .requestBody(new RequestBody()
                                            .description("Dados do usuário para registro")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/UsuarioRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("201", new ApiResponse().description("Usuário registrado com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))
                                    )
                            )
                    )
                    .path("/api/auth/sign-in", new PathItem().post(new Operation()
                                    .summary("Realiza login")
                                    .addTagsItem("Auth")
                                    .requestBody(new RequestBody()
                                            .description("Dados do usuário para login")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/UsuarioLoginRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Usuário logado com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))
                                    )
                            )
                    )
                    .path("/api/test", new PathItem().get(new Operation()
                                    .summary("Realiza login independente da 'role' (administrador ou paciente)")
                                    .addTagsItem("Testes")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Teste realizado com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))
                                    )
                            )
                    )
                    .path("/api/test/administrador", new PathItem().get(new Operation()
                                    .summary("Realiza login como 'administrador'")
                                    .addTagsItem("Testes")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Teste realizado como administrador com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))
                                    )
                            )
                    )
                    .path("/api/test/paciente", new PathItem().get(new Operation()
                                    .summary("Realiza login como 'paciente'")
                                    .addTagsItem("Testes")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Teste realizado como paciente com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))
                                    )
                            )
                    )

                    // ---- Medicamentos ----
                    .path("/api/medicamentos", new PathItem()
                            .post(new Operation()
                                    .summary("Cadastra um novo medicamento")
                                    .addTagsItem("Medicamentos")
                                    .requestBody(new RequestBody()
                                            .description("Dados do medicamento")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/MedicamentoRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("201", new ApiResponse().description("Medicamento cadastrado com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .get(new Operation()
                                    .summary("Lista todos os medicamentos")
                                    .addTagsItem("Medicamentos")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Lista de medicamentos retornada com sucesso"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
                    .path("/api/medicamentos/{id}", new PathItem()
                            .get(new Operation()
                                    .summary("Busca medicamento por ID")
                                    .addTagsItem("Medicamentos")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Medicamento encontrado"))
                                            .addApiResponse("404", new ApiResponse().description("Medicamento não encontrado"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .put(new Operation()
                                    .summary("Atualiza um medicamento")
                                    .addTagsItem("Medicamentos")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .requestBody(new RequestBody()
                                            .description("Dados atualizados do medicamento")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/MedicamentoRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Medicamento atualizado com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Medicamento não encontrado"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .delete(new Operation()
                                    .summary("Deleta um medicamento")
                                    .addTagsItem("Medicamentos")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("204", new ApiResponse().description("Medicamento deletado com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Medicamento não encontrado"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
                    .path("/api/medicamentos/disponibilidade", new PathItem()
                            .post(new Operation()
                                    .summary("Verifica disponibilidade de um medicamento")
                                    .addTagsItem("Medicamentos")
                                    .requestBody(new RequestBody()
                                            .description("Nome do medicamento para verificar")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/DisponibilidadeRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Disponibilidade verificada com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )

                    // ---- Estoques ----
                    .path("/api/estoques", new PathItem()
                            .post(new Operation()
                                    .summary("Cadastra um novo registro de estoque")
                                    .addTagsItem("Estoques")
                                    .requestBody(new RequestBody()
                                            .description("Dados do estoque")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/EstoqueRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("201", new ApiResponse().description("Estoque cadastrado com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .get(new Operation()
                                    .summary("Lista todos os registros de estoque")
                                    .addTagsItem("Estoques")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Lista de estoques retornada com sucesso"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
                    .path("/api/estoques/{id}", new PathItem()
                            .get(new Operation()
                                    .summary("Busca estoque por ID")
                                    .addTagsItem("Estoques")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Estoque encontrado"))
                                            .addApiResponse("404", new ApiResponse().description("Estoque não encontrado"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .put(new Operation()
                                    .summary("Atualiza um registro de estoque")
                                    .addTagsItem("Estoques")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .requestBody(new RequestBody()
                                            .description("Dados atualizados do estoque")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/EstoqueRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Estoque atualizado com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Estoque não encontrado"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .delete(new Operation()
                                    .summary("Deleta um registro de estoque")
                                    .addTagsItem("Estoques")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("204", new ApiResponse().description("Estoque deletado com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Estoque não encontrado"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )

                    // ---- Unidades ----
                    .path("/api/unidades", new PathItem()
                            .post(new Operation()
                                    .summary("Cadastra uma nova unidade")
                                    .addTagsItem("Unidades")
                                    .requestBody(new RequestBody()
                                            .description("Dados da unidade")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/UnidadeRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("201", new ApiResponse().description("Unidade cadastrada com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .get(new Operation()
                                    .summary("Lista todas as unidades")
                                    .addTagsItem("Unidades")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Lista de unidades retornada com sucesso"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
                    .path("/api/unidades/{id}", new PathItem()
                            .get(new Operation()
                                    .summary("Busca unidade por ID")
                                    .addTagsItem("Unidades")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Unidade encontrada"))
                                            .addApiResponse("404", new ApiResponse().description("Unidade não encontrada"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .put(new Operation()
                                    .summary("Atualiza uma unidade")
                                    .addTagsItem("Unidades")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .requestBody(new RequestBody()
                                            .description("Dados atualizados da unidade")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/UnidadeRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Unidade atualizada com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Unidade não encontrada"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .delete(new Operation()
                                    .summary("Deleta uma unidade")
                                    .addTagsItem("Unidades")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("204", new ApiResponse().description("Unidade deletada com sucesso"))
                                            .addApiResponse("404", new ApiResponse().description("Unidade não encontrada"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )

                    // ---- Movimentações ----
                    .path("/api/movimentacoes", new PathItem()
                            .post(new Operation()
                                    .summary("Registra uma nova movimentação de estoque")
                                    .addTagsItem("Movimentações")
                                    .requestBody(new RequestBody()
                                            .description("Dados da movimentação")
                                            .required(true)
                                            .content(new Content().addMediaType("application/json", new MediaType()
                                                    .schema(new Schema().$ref("#/components/schemas/MovimentacaoRequestDTO")))))
                                    .responses(new ApiResponses()
                                            .addApiResponse("201", new ApiResponse().description("Movimentação registrada com sucesso"))
                                            .addApiResponse("400", new ApiResponse().description("Requisição inválida"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                            .get(new Operation()
                                    .summary("Lista todas as movimentações")
                                    .addTagsItem("Movimentações")
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Lista de movimentações retornada com sucesso"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
                    .path("/api/movimentacoes/{id}", new PathItem()
                            .get(new Operation()
                                    .summary("Busca movimentação por ID")
                                    .addTagsItem("Movimentações")
                                    .addParametersItem(new Parameter().name("id").in("path").required(true).schema(new Schema<Integer>().type("integer")))
                                    .responses(new ApiResponses()
                                            .addApiResponse("200", new ApiResponse().description("Movimentação encontrada"))
                                            .addApiResponse("404", new ApiResponse().description("Movimentação não encontrada"))
                                            .addApiResponse("403", new ApiResponse().description("Acesso negado"))
                                            .addApiResponse("500", new ApiResponse().description("Erro interno do servidor"))))
                    )
            ;
        };
    }
}
